### PR TITLE
fix/some-locations-crash-app

### LINKED ISSUE #16: Some locations crash the page
I have tried to input 'north pole' and 'south pole'. Both of these locations crash the page. 

Potentially an issue with sunset/sunrise or timezones?

### LINKED ISSUE #37: SunPosition shouldn't be numerical if the sun has set
SunPosition should be set to invisible if the sun has set - instead of position 1000 - 1000....

### PR DESCRIPTION
**Pull request by JordT**
# 🟢 Ready for review and merge  🟢 

Branch will close #16, some locations are causing the apps to crash.

## The issue:
Identified that DateTime is calling fromSeconds(), when DateTime isn't available React stops rendering to avoid incorrectly rendering components. This has been in place since React 16.

### Current Progress
- Added ErrorBoundary component, this means errors caught in child components are rendered as a caught error rather than all the components crashing.

### Next Steps
- Implement error catching in the SunPosition component so if DateTime.fromSeconds() fails we don't render an error message.

### CODE REVIEW

**Comment by JordT** [comment]
Rebase is not the way. Merged main branch in local working branch

https://www.togaware.com/linux/survivor/Git_Merge_Master_into.html

**Comment by JordT** [comment]
Unable to test branch as we're now running a backend server and I don't have the .env file :( @mr-jackpot please review and test 👍

**Comment by JordT** [comment]
Had a shower thought, my solution is trash, needs to use state... Will sort tonight

**Comment by JordT** [comment]
Closes #37 

- changed sun to hidden if its set
- Fixed crashing if no sunset/sunrise data provided
- added error boundary to all components
- tidied comments

**Review by mr-jackpot — APPROVED** [review]
As discussed on the call, great work and thanks for giving me a wee KT. Good spot finding that the north pole doesnt send any data... the sun rises once a year!

ErrorBoundary looking good and seems like we should be including this as standard. We should try test it somehow 😄

**Pull request merged**
